### ISSUE TITLE
Where is the documentation for this repository?

### ISSUE THREAD

**Issue by PrasadNR** [manuel-calzolari/sklearn-genetic#10]
I am having a difficult time understanding why estimator is needed in the first place.

**Comment by manuel-calzolari** [comment]
At the moment, there's a code example in the README file and there are docstrings in the source code, but I still have to generate the documentation.

An estimator is needed because this is basically a wrapper feature selection method, see https://sebastianraschka.com/faq/docs/feature_sele_categories.html

**Comment by manuel-calzolari** [comment]
I've generated some initial documentation: https://sklearn-genetic.readthedocs.io
