### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by joeyned** [manuel-calzolari/sklearn-genetic#39]
np.bool is now deprecated, instead numpy package only uses the built in bool python function. This means the package does not work anymore.

**Comment by musicinmybrain** [comment]
Here is the documentation for the change in the [Numpy 1.20 release notes](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

Since `np.bool` aliased the Python `bool`, using it instead is the safest, 100% API-compatible adaptation. (For cases not exposed to the user, it could be that the memory savings of using `np.bool_`, which is stored as a byte rather than an integer, could be worthwhile.)

I’ll open a PR to replaces all cases of `np.bool` with `bool`.

**Comment by detrin** [comment]
will be solved in https://github.com/manuel-calzolari/sklearn-genetic/pull/41

**Comment by manuel-calzolari** [comment]
Closed with commit 12ee9b2. Thank you!

**Comment by musicinmybrain** [comment]
> Closed with commit [12ee9b2](https://github.com/manuel-calzolari/sklearn-genetic/commit/12ee9b2e591ec379793bcff1966095b43dac10c6). Thank you!

Thank you! This works very nicely. I’m packaging a snapshot of that commit in Fedora Linux, and I look forward to the next official release.

**Comment by manuel-calzolari** [comment]
> Thank you! This works very nicely. I’m packaging a snapshot of that commit in Fedora Linux, and I look forward to the next official release.

@musicinmybrain Version 0.6.0 has been released

**Comment by musicinmybrain** [comment]
> > Thank you! This works very nicely. I’m packaging a snapshot of that commit in Fedora Linux, and I look forward to the next official release.
> 
> @musicinmybrain Version 0.6.0 has been released

Thank you! I just proposed an update for the Fedora Linux package. Allowing time for the primary maintainer to review the PR and time spent in `updates-testing`, it should be in stable Fedora releases in roughly a couple of weeks.
